// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdvvNv0yo8M_CpsBIj5CnxSZqNhEAB97U',
    appId: '1:118196721366:web:c1a766e265f50a8fad9b77',
    messagingSenderId: '118196721366',
    projectId: 'flutter-login-app-b9d99',
    authDomain: 'flutter-login-app-b9d99.firebaseapp.com',
    storageBucket: 'flutter-login-app-b9d99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9KWz4VndxHIA-YWg97Q4OvX6iy0HnRSQ',
    appId: '1:118196721366:android:a2f7ff807fba05caad9b77',
    messagingSenderId: '118196721366',
    projectId: 'flutter-login-app-b9d99',
    storageBucket: 'flutter-login-app-b9d99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7yMNpeynHAUvsqow5LZ8wfTllwqM_0Sc',
    appId: '1:118196721366:ios:6b82747756251621ad9b77',
    messagingSenderId: '118196721366',
    projectId: 'flutter-login-app-b9d99',
    storageBucket: 'flutter-login-app-b9d99.appspot.com',
    iosClientId: '118196721366-ltki6flhvl0qo4k8k1kbc3dmti71u8c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7yMNpeynHAUvsqow5LZ8wfTllwqM_0Sc',
    appId: '1:118196721366:ios:6b82747756251621ad9b77',
    messagingSenderId: '118196721366',
    projectId: 'flutter-login-app-b9d99',
    storageBucket: 'flutter-login-app-b9d99.appspot.com',
    iosClientId: '118196721366-ltki6flhvl0qo4k8k1kbc3dmti71u8c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginApp',
  );
}
